
# Gem::Specification for Shoulda-4.1.2
# Originally generated by Echoe

--- !ruby/object:Gem::Specification 
name: shoulda
version: !ruby/object:Gem::Version 
  version: 4.1.2
platform: ruby
authors: 
- Tammer Saleh
autorequire: 
bindir: bin

date: 2008-09-12 00:00:00 -04:00
default_executable: 
dependencies: 
- !ruby/object:Gem::Dependency 
  name: echoe
  type: :development
  version_requirement: 
  version_requirements: !ruby/object:Gem::Requirement 
    requirements: 
    - - ">="
      - !ruby/object:Gem::Version 
        version: "0"
    version: 
description: Testing made easier on the fingers and the eyes, in gem form
email: ""
executables: 
- convert_to_should_syntax
extensions: []

extra_rdoc_files: 
- bin/convert_to_should_syntax
- lib/shoulda/action_mailer/assertions.rb
- lib/shoulda/action_mailer.rb
- lib/shoulda/active_record/assertions.rb
- lib/shoulda/active_record/macros.rb
- lib/shoulda/active_record.rb
- lib/shoulda/assertions.rb
- lib/shoulda/context.rb
- lib/shoulda/controller/formats/html.rb
- lib/shoulda/controller/formats/xml.rb
- lib/shoulda/controller/helpers.rb
- lib/shoulda/controller/macros.rb
- lib/shoulda/controller/resource_options.rb
- lib/shoulda/controller.rb
- lib/shoulda/helpers.rb
- lib/shoulda/macros.rb
- lib/shoulda/private_helpers.rb
- lib/shoulda/proc_extensions.rb
- lib/shoulda/rails.rb
- lib/shoulda.rb
- README.rdoc
- tasks/list_tests.rake
- tasks/yaml_to_shoulda.rake
files: 
- bin/convert_to_should_syntax
- CONTRIBUTION_GUIDELINES.rdoc
- init.rb
- lib/shoulda/action_mailer/assertions.rb
- lib/shoulda/action_mailer.rb
- lib/shoulda/active_record/assertions.rb
- lib/shoulda/active_record/macros.rb
- lib/shoulda/active_record.rb
- lib/shoulda/assertions.rb
- lib/shoulda/context.rb
- lib/shoulda/controller/formats/html.rb
- lib/shoulda/controller/formats/xml.rb
- lib/shoulda/controller/helpers.rb
- lib/shoulda/controller/macros.rb
- lib/shoulda/controller/resource_options.rb
- lib/shoulda/controller.rb
- lib/shoulda/helpers.rb
- lib/shoulda/macros.rb
- lib/shoulda/private_helpers.rb
- lib/shoulda/proc_extensions.rb
- lib/shoulda/rails.rb
- lib/shoulda.rb
- Manifest
- MIT-LICENSE
- rails/init.rb
- Rakefile
- README.rdoc
- shoulda.gemspec
- tasks/list_tests.rake
- tasks/yaml_to_shoulda.rake
- test/fixtures/addresses.yml
- test/fixtures/friendships.yml
- test/fixtures/posts.yml
- test/fixtures/products.yml
- test/fixtures/taggings.yml
- test/fixtures/tags.yml
- test/fixtures/users.yml
- test/functional/posts_controller_test.rb
- test/functional/users_controller_test.rb
- test/other/context_test.rb
- test/other/convert_to_should_syntax_test.rb
- test/other/helpers_test.rb
- test/other/private_helpers_test.rb
- test/other/should_test.rb
- test/rails_root/app/controllers/application.rb
- test/rails_root/app/controllers/posts_controller.rb
- test/rails_root/app/controllers/users_controller.rb
- test/rails_root/app/helpers/application_helper.rb
- test/rails_root/app/helpers/posts_helper.rb
- test/rails_root/app/helpers/users_helper.rb
- test/rails_root/app/models/address.rb
- test/rails_root/app/models/dog.rb
- test/rails_root/app/models/flea.rb
- test/rails_root/app/models/friendship.rb
- test/rails_root/app/models/post.rb
- test/rails_root/app/models/product.rb
- test/rails_root/app/models/tag.rb
- test/rails_root/app/models/tagging.rb
- test/rails_root/app/models/user.rb
- test/rails_root/app/views/layouts/posts.rhtml
- test/rails_root/app/views/layouts/users.rhtml
- test/rails_root/app/views/posts/edit.rhtml
- test/rails_root/app/views/posts/index.rhtml
- test/rails_root/app/views/posts/new.rhtml
- test/rails_root/app/views/posts/show.rhtml
- test/rails_root/app/views/users/edit.rhtml
- test/rails_root/app/views/users/index.rhtml
- test/rails_root/app/views/users/new.rhtml
- test/rails_root/app/views/users/show.rhtml
- test/rails_root/config/boot.rb
- test/rails_root/config/database.yml
- test/rails_root/config/environment.rb
- test/rails_root/config/environments/sqlite3.rb
- test/rails_root/config/initializers/new_rails_defaults.rb
- test/rails_root/config/initializers/shoulda.rb
- test/rails_root/config/routes.rb
- test/rails_root/db/migrate/001_create_users.rb
- test/rails_root/db/migrate/002_create_posts.rb
- test/rails_root/db/migrate/003_create_taggings.rb
- test/rails_root/db/migrate/004_create_tags.rb
- test/rails_root/db/migrate/005_create_dogs.rb
- test/rails_root/db/migrate/006_create_addresses.rb
- test/rails_root/db/migrate/007_create_fleas.rb
- test/rails_root/db/migrate/008_create_dogs_fleas.rb
- test/rails_root/db/migrate/009_create_products.rb
- test/rails_root/db/migrate/010_create_friendships.rb
- test/rails_root/db/schema.rb
- test/rails_root/public/404.html
- test/rails_root/public/422.html
- test/rails_root/public/500.html
- test/rails_root/script/console
- test/rails_root/script/generate
- test/README
- test/test_helper.rb
- test/unit/address_test.rb
- test/unit/dog_test.rb
- test/unit/flea_test.rb
- test/unit/friendship_test.rb
- test/unit/post_test.rb
- test/unit/product_test.rb
- test/unit/tag_test.rb
- test/unit/tagging_test.rb
- test/unit/user_test.rb
has_rdoc: true
homepage: http://thoughtbot.com/projects/shoulda
post_install_message: 
rdoc_options: 
- --line-numbers
- --inline-source
- --title
- Shoulda
- --main
- README.rdoc
require_paths: 
- lib
required_ruby_version: !ruby/object:Gem::Requirement 
  requirements: 
  - - ">="
    - !ruby/object:Gem::Version 
      version: "0"
  version: 
required_rubygems_version: !ruby/object:Gem::Requirement 
  requirements: 
  - - "="
    - !ruby/object:Gem::Version 
      version: "1.2"
  version: 
requirements: []

rubyforge_project: shoulda
rubygems_version: 1.2.0
specification_version: 2
summary: Testing made easier on the fingers and the eyes, in gem form
test_files: 
- test/functional/posts_controller_test.rb
- test/functional/users_controller_test.rb
- test/other/context_test.rb
- test/other/convert_to_should_syntax_test.rb
- test/other/helpers_test.rb
- test/other/private_helpers_test.rb
- test/other/should_test.rb
- test/unit/address_test.rb
- test/unit/dog_test.rb
- test/unit/flea_test.rb
- test/unit/friendship_test.rb
- test/unit/post_test.rb
- test/unit/product_test.rb
- test/unit/tag_test.rb
- test/unit/tagging_test.rb
- test/unit/user_test.rb
